### ISSUE TITLE
Failed to load plugin 'python.hk'

### ISSUE THREAD

**Issue by benjamintanweihao** [philkr/gamehook#6]
All the other plugins (`capture.hk` and `server.hk`) work fine, except for `python.hk`, where I get a `Failed to load plugin 'python.hk'` error. How do I debug this? I have successfully built `pyhook` too.

**Comment by bradyz** [comment]
If "LoadLibrary" fails,  chances are the plugin is not able to find "python*.dll" at runtime.

To solve this, you'll have to add this directory to the windows environmental variable PATH through the control panel and restart your computer (env vars are reloaded by restart).

Since I'm using python installed by visual studio, I added

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64

**Comment by benjamintanweihao** [comment]
It works! 🕺
